import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import TabsComponent from '@/components/TabsComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen pt-14 max-w-7xl m-auto">

        <Navbar/>
          <div className="z-10 max-w-5xl pt-10  m-auto w-full font-mono text-sm">
            <TabsComponent/>
            {children}
          </div>  
        </div>
      </body>
    </html>
  )
}
